services:
  FullStackApplication:
    image: fullstackapplication
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: FullStackApplication/Dockerfile
  ollama:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    environment:
      OLLAMA_CONTEXT_LENGTH: "4096"
    restart: unless-stopped
volumes:
  ollama: